//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SU_MT2000_SUIDScanner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SU_MT2000_SUIDScanner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string StrAbout {
            get {
                return ResourceManager.GetString("StrAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string StrBarcode {
            get {
                return ResourceManager.GetString("StrBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string StrCancel {
            get {
                return ResourceManager.GetString("StrCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Delay.
        /// </summary>
        internal static string StrClearDelay {
            get {
                return ResourceManager.GetString("StrClearDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string StrClose {
            get {
                return ResourceManager.GetString("StrClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma.
        /// </summary>
        internal static string StrComma {
            get {
                return ResourceManager.GetString("StrComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        internal static string StrDeleteAll {
            get {
                return ResourceManager.GetString("StrDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Item.
        /// </summary>
        internal static string StrDeleteItem {
            get {
                return ResourceManager.GetString("StrDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string StrDone {
            get {
                return ResourceManager.GetString("StrDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string StrEdit {
            get {
                return ResourceManager.GetString("StrEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Item.
        /// </summary>
        internal static string StrEditItem {
            get {
                return ResourceManager.GetString("StrEditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to scanner services. Please try again..
        /// </summary>
        internal static string StrErrorCantSetScannerServicesMode {
            get {
                return ResourceManager.GetString("StrErrorCantSetScannerServicesMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to scanner services. Please try again..
        /// </summary>
        internal static string StrErrorCantStartScannerServices {
            get {
                return ResourceManager.GetString("StrErrorCantStartScannerServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a barcode..
        /// </summary>
        internal static string StrErrorNoBarcode {
            get {
                return ResourceManager.GetString("StrErrorNoBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an export file name..
        /// </summary>
        internal static string StrErrorNoExportFile {
            get {
                return ResourceManager.GetString("StrErrorNoExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a location..
        /// </summary>
        internal static string StrErrorNoLocation {
            get {
                return ResourceManager.GetString("StrErrorNoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanner Services is not running..
        /// </summary>
        internal static string StrErrorScannerServicesNotRunning {
            get {
                return ResourceManager.GetString("StrErrorScannerServicesNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string StrExport {
            get {
                return ResourceManager.GetString("StrExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inventory was successfully exported to {0}..
        /// </summary>
        internal static string StrExportOK {
            get {
                return ResourceManager.GetString("StrExportOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string StrFile {
            get {
                return ResourceManager.GetString("StrFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string StrFormat {
            get {
                return ResourceManager.GetString("StrFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouped.
        /// </summary>
        internal static string StrGrouped {
            get {
                return ResourceManager.GetString("StrGrouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string StrItem {
            get {
                return ResourceManager.GetString("StrItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string StrLocation {
            get {
                return ResourceManager.GetString("StrLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string StrMenu {
            get {
                return ResourceManager.GetString("StrMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string StrNo {
            get {
                return ResourceManager.GetString("StrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string StrOK {
            get {
                return ResourceManager.GetString("StrOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete ALL the items?.
        /// </summary>
        internal static string StrOKToDeleteAll {
            get {
                return ResourceManager.GetString("StrOKToDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected item?.
        /// </summary>
        internal static string StrOKToDeleteItem {
            get {
                return ResourceManager.GetString("StrOKToDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string StrOptions {
            get {
                return ResourceManager.GetString("StrOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string StrQuantity {
            get {
                return ResourceManager.GetString("StrQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  s.
        /// </summary>
        internal static string StrS {
            get {
                return ResourceManager.GetString("StrS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string StrSave {
            get {
                return ResourceManager.GetString("StrSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Inventory.
        /// </summary>
        internal static string StrSaveInventory {
            get {
                return ResourceManager.GetString("StrSaveInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inventory was successfully saved..
        /// </summary>
        internal static string StrSaveOK {
            get {
                return ResourceManager.GetString("StrSaveOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUID Scanning.
        /// </summary>
        internal static string StrScanInventory {
            get {
                return ResourceManager.GetString("StrScanInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string StrSeconds {
            get {
                return ResourceManager.GetString("StrSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semi-colon.
        /// </summary>
        internal static string StrSemiColon {
            get {
                return ResourceManager.GetString("StrSemiColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator.
        /// </summary>
        internal static string StrSeparator {
            get {
                return ResourceManager.GetString("StrSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        internal static string StrTab {
            get {
                return ResourceManager.GetString("StrTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string StrText {
            get {
                return ResourceManager.GetString("StrText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmit.
        /// </summary>
        internal static string StrTransmit {
            get {
                return ResourceManager.GetString("StrTransmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Inventory.
        /// </summary>
        internal static string StrViewInventory {
            get {
                return ResourceManager.GetString("StrViewInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string StrXML {
            get {
                return ResourceManager.GetString("StrXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string StrYes {
            get {
                return ResourceManager.GetString("StrYes", resourceCulture);
            }
        }
    }
}
